// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: vstone

#ifndef SIMULATOR

#ifndef _BACKLIGHT_H
#define _BACKLIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

extern bool flg_als_Enable;
extern bool flg_disp_inactive;
extern bool flg_process_als; // flag control to call set_backlight_als from ui.ino loop

extern bool flg_alert2d_display; // flag to indicate if the hardware is related to alert2d display
                                 // or nkd display

void backlight_init(uint8_t pin);
void set_backlight(uint32_t dutycycle);
void als_init();
void als_on();
void als_off();
void set_backlight_als();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

#endif // #ifndef SIMULATOR